# Generated by Django 4.2.3 on 2023-07-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0002_project_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fecha_modificacion',
            field=models.DateField(),
        ),
    ]
